---
title: "China privacy study: initial results"
format:
  html:
    toc: true
    toc-location: left
---

```{r setup, message=FALSE, warning=FALSE, echo=FALSE, error=FALSE}
library(tidyverse)
library(kableExtra)
library(modelsummary)

knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(error = FALSE)

load(file="privacy.RData")

Ones <- function(x) table(x)[1]
Twos <- function(x) table(x)[2]
Threes <- function(x) table(x)[3]
Fours <- function(x) table(x)[4]
Fives <- function(x) table(x)[5]
Sixes <- function(x) table(x)[6]
Sevens <- function(x) table(x)[7]
```

## Demographics

```{r demoqs}
#| label: tbl-demo.q.text
#| tbl-cap: Demographic questions

table.text <- list()

table.text[[1]] <- c("Q1", "Which of these best describes the place in which you live?")
table.text[[2]] <- c("Q2", "What province do you live in?")
table.text[[3]] <- c("Q3", "How old are you?")
table.text[[4]] <- c("Q4", "What is the highest level of education that you have obtained?")
table.text[[5]] <- c("Q5", "Gender")
table.text[[6]] <- c("Q6", "Marital Status")
table.text[[7]] <- c("Q7", "Which of the following best describes the type of job you have?")
table.text[[8]] <- c("Q8", "Which of the following best describes the type of company or work unit you work for?")
table.text[[9]] <- c("Q9", "Are you a member or probationary member of the CCP?")
table.text[[10]] <- c("Q10", "Are you a member of the Communist Youth League?")
table.text[[11]] <- c("Q11", "Here is a table showing the range of monthly incomes that people have. Which of the letters on this table best represents the total monthly income of your household (after tax)?")
table.text[[12]] <- c("Q12", "What is your residency status?")

demo.text <- data.frame()

for(line in table.text) {
  demo.text <- rbind(demo.text, line)
}

kbl(demo.text, col.names = NULL) %>% 
  kable_styling()
```

```{r demosummary}
#| label: tbl-demo.summary.data
#| tbl-cap: Demographic summary data

demo.qs <- privacy %>% 
  select(`Location` = location,
         `Province` = province,
         `Age` = age,
         `Education` = education,
         `Gender` = sex,
         `Marriage status` = marriage.status,
         `Job type` = job.type,
         `Company type` = job.company.type,
         `Party member status` = party.member.status,
         `Communist Youth League status` = cyl.status,
         `Income` = income,
         `Hukou status` = hukou.status) 

datasummary_balance( ~ 1, data=demo.qs)
```

## Knowledge questions

```{r kwqs}
#| label: tbl-kw.q.text
#| tbl-cap: Privacy knowledge questions

table.text <- list()

table.text[[1]] <- c("Q1", "I am very concerned about my privacy online")
(example: paying for something online – worried that a criminal might steal my payment information)
")
table.text[[4]] <- c("Q4", "I spend a lot of time reading about technology related privacy issues")
table.text[[5]] <- c("Q5", "In the last year, I have had discussions with my friends about online privacy issues")
table.text[[6]] <- c("Q6", "I feel like I know exactly how much privacy I have online")
table.text[[7]] <- c("Q7", "Have you heard of the social credit system (official terminology)?")
table.text[[8]] <- c("Q8", "Based on your knowledge of the social credit system please list some actions that you believe would lower your social credit")
table.text[[9]] <- c("Q9", "Based on your knowledge of the social credit system, please list some actions that you believe would be more difficult or prohibited if you have a low social credit score")
table.text[[10]] <- c("Q10", "Privacy knowledge index of Q1 + Q4 + Q5 + Q6 + Q7")

kw.text <- data.frame()

for(line in table.text) {
  kw.text <- rbind(kw.text, line)
}

kbl(kw.text, col.names = NULL) %>% 
  kable_styling()
```

```{r kwsummary}
#| label: tbl-kw.summary.data
#| tbl-cap: Privacy knowledge summary data

#| label: tbl-gp.summary.data
#| tbl-cap: Government performance summary data

k.qs <- privacy %>% 
  mutate(k1 = as.numeric(k1)) %>% 
  mutate(k4 = as.numeric(k4)) %>% 
  mutate(k5 = as.numeric(k5)) %>% 
  mutate(k6 = as.numeric(k6)) %>% 
  mutate(k7 = as.numeric(k7)) %>% 
  select(`General privacy concern` = k1,
         `Reading about privacy` = k4,
         `Discuss privacy with friends` = k5,
         `Privacy feeling online` = k6,
         `Heard of social credit?` = k7) 

datasummary(All(k.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=k.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))

k.index.q <- privacy %>% 
  select(`Privacy index` = k.index) 

datasummary(All(k.index.q) ~ Mean + SD + Histogram, data=k.index.q)
```

## Personality questions

```{r pqs}
#| label: tbl-p.q.text
#| tbl-cap: Personality questions

table.text <- list()

table.text[[1]] <- c("Q1", "Power Distance: In choosing an ideal job, it is important for me to have a good working relationship with my superior.")
table.text[[2]] <- c("Q2", "Power Distance: When I have a disagreement with my superior it is important for me to be able to express it to them.")
table.text[[3]] <- c("Q3", "Individualism vs. Collectivism (Personal vs. Job): In choosing an ideal job, it is important for me to have sufficient time for my personal or family life.")
table.text[[4]] <- c("Q4", "Individualism vs. Collectivism (Personal vs. Job): Having a job with variety and adventure is more important to me than having a secure and stable job.")
table.text[[5]] <- c("Q5", "Masculinity vs. Femininity (Trust vs. Risk): Most people can be trusted.")
table.text[[6]] <- c("Q6", "Masculinity vs. Femininity (Trust vs. Risk): When people have failed in life it is often their own fault.")
table.text[[7]] <- c("Q7", "Uncertainty Avoidance: I prefer my manager to give me strict instructions on how to do my work.")
table.text[[8]] <- c("Q8", "Uncertainty Avoidance: Competition between employees usually does more harm than good.")
table.text[[9]] <- c("Q9", "Long-term Orientation: In your private life, how important is thrift?")
table.text[[10]] <- c("Q10", "Long-term Orientation: In your private life, how important is respect for tradition?")
table.text[[11]] <- c("Q11", "Power Distance Index")
table.text[[12]] <- c("Q12", "Individualism Index")
table.text[[13]] <- c("Q13", "Masculinity Index")
table.text[[14]] <- c("Q14", "Uncertainty Avoidance Index")
table.text[[15]] <- c("Q15", "Long-term Orientation Index")

p.text <- data.frame()

for(line in table.text) {
  p.text <- rbind(p.text, line)
}

kbl(p.text, col.names = NULL) %>% 
  kable_styling()
```

```{r psummary}
#| label: tbl-p.summary.data
#| tbl-cap: Personality summary data

p.qs <- privacy %>% 
  mutate(p.pd1 = as.numeric(p.pd1)) %>% 
  mutate(p.pd2 = as.numeric(p.pd2)) %>% 
  mutate(p.ic1 = as.numeric(p.ic1)) %>% 
  mutate(p.ic2 = as.numeric(p.ic2)) %>% 
  mutate(p.mf1 = as.numeric(p.mf1)) %>% 
  mutate(p.mf2 = as.numeric(p.mf2)) %>%
  mutate(p.ua1 = as.numeric(p.ua1)) %>%
  mutate(p.ua2 = as.numeric(p.ua2)) %>%
  mutate(p.lo1 = as.numeric(p.lo1)) %>%
  mutate(p.lo2 = as.numeric(p.lo2)) %>%
  select(`Power Distance Q1` = p.pd1,
         `Power Distance Q2` = p.pd2,
         `Individualism Q1` = p.ic1,
         `Individualism Q2` = p.ic2,
         `Masculinity Q1` = p.mf1,
         `Masculinity Q2` = p.mf2,
         `Uncertainty Avoidance Q1` = p.ua1,
         `Uncertainty Avoidance Q2` = p.ua2,
         `Long-term Orientation Q1` = p.lo1,
         `Long-term Orientation Q2` = p.lo2) 

datasummary(All(p.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=p.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))

p.index.q <- privacy %>% 
  select(`Power Distance index` = p.pd.index,
         `Individualism index` = p.ic.index,
         `Masculinity index` = p.mf.index,
         `Uncertainty Avoidance index` = p.ua.index,
         `Long-term Orientation index` = p.lo.index,) 

datasummary(All(p.index.q) ~ Mean + SD + Histogram, data=p.index.q)
```


## Government performance

```{r gpqs}
#| label: tbl-gp.q.text
#| tbl-cap: Government performance questions

table.text <- list()

table.text[[1]] <- c("Q1", "Overall, I’m happy with the performance of the central government")
table.text[[2]] <- c("Q2", "Overall, I’m happy with the performance of my local government")
table.text[[3]] <- c("Q3", "The government does a good job balancing the rights of citizens to be free of surveillance in their daily lives with the need to preserve order and prevent crime.")
table.text[[4]] <- c("Q4", "Government performance index")

gp.text <- data.frame()

for(line in table.text) {
  gp.text <- rbind(gp.text, line)
}

kbl(gp.text, col.names = NULL) %>% 
  kable_styling()
```

```{r gpsummary}
#| label: tbl-gp.summary.data
#| tbl-cap: Government performance summary data

gp.qs <- privacy %>% 
  mutate(gp1 = as.numeric(gp1)) %>% 
  mutate(gp2 = as.numeric(gp2)) %>% 
  mutate(gp3 = as.numeric(gp3)) %>% 
  select(`Central government performance` = gp1,
         `Local government performance` = gp2,
         `Government performance Q3` = gp3) 

datasummary(All(gp.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=gp.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))

gp.index.q <- privacy %>% 
  select(`Government performance index` = gp.index) 

datasummary(All(gp.index.q) ~ Mean + SD + Histogram, data=gp.index.q)
```

## Media attention

```{r mas}
#| label: tbl-ma.q.text
#| tbl-cap: Media attention questions

table.text <- list()

table.text[[1]] <- c("Q1", "How often do you read news articles?")
table.text[[2]] <- c("Q2", "What is your primary source for news?")

ma.text <- data.frame()

for(line in table.text) {
  ma.text <- rbind(ma.text, line)
}

kbl(ma.text, col.names = NULL) %>% 
  kable_styling()
```

```{r masummary}
#| label: tbl-ma.summary.data
#| tbl-cap: Media attention summary data

ma.qs <- privacy %>% 
  select(`Read news frequency` = ma1,
         `News primary source` = ma2) 

datasummary_balance( ~ 1, data=ma.qs)
```

## Government and private monitoring

```{r mas}
#| label: tbl-gm.q.text
#| tbl-cap: Government and private monitoring questions

table.text <- list()

table.text[[1]] <- c("Q1", "There are good reasons for the central government to monitor the activity of users online")
table.text[[2]] <- c("Q2", "There are good reasons for the local government to monitor the activity of users online")
table.text[[3]] <- c("Q3", "There are good reasons for private companies to monitor the activity of users online")
table.text[[4]] <- c("Q4", "It doesn’t bother me to provide the government with biometric information including my fingerprints and face details for the purposes of monitoring public places")
table.text[[5]] <- c("Q5", "It doesn’t bother me to provide private companies with biometric information including my fingerprints and face details for the purposes of monitoring public places")
table.text[[6]] <- c("Q6", "Government monitoring index of Q1 + Q2 + Q4")
table.text[[7]] <- c("Q7", "Private monitoring index of Q3 + Q5")
table.text[[8]] <- c("Q8", "Total monitoring index of Q1-Q5")

gm.text <- data.frame()

for(line in table.text) {
  gm.text <- rbind(gm.text, line)
}

kbl(gm.text, col.names = NULL) %>% 
  kable_styling()
```

```{r masummary}
#| label: tbl-gm.summary.data
#| tbl-cap: Government and private monitoring summary data

gm.qs <- privacy %>% 
  mutate(gm1 = as.numeric(gm1)) %>% 
  mutate(gm2 = as.numeric(gm2)) %>% 
  mutate(gm3 = as.numeric(gm3)) %>% 
  mutate(gm4 = as.numeric(gm4)) %>% 
  mutate(gm5 = as.numeric(gm5)) %>% 
  select(`Central government monitoring` = gm1,
         `Local government monitoring` = gm2,
         `Private company monitoring` = gm3,
         `Government biometric monitoring` = gm4,
         `Private biometric monitoring` = gm5) 

datasummary(All(gm.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=gm.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))

gm.index.q <- privacy %>% 
  select(`Government monitoring index` = gm.index.gov,
         `Private monitoring index` = gm.index.priv,
         `Total monitoring index` = gm.index.total) 

datasummary(All(gm.index.q) ~ Mean + SD + Histogram, data=gm.index.q)
```

## Tech savvy

```{r gpqs}
#| label: tbl-ts.q.text
#| tbl-cap: Tech savvy questions

table.text <- list()

table.text[[1]] <- c("Q1", "How would you rate your general ability to use a computer?")
table.text[[2]] <- c("Q2", "How would you rate your skill at fixing a computer? ")
table.text[[3]] <- c("Q3", "How would you rate your ability to program a computer? ")
table.text[[4]] <- c("Q4", "How widely do think facial recognition technology is deployed?")
table.text[[4]] <- c("Q5", "Tech savvy index of Q1 + Q2 + Q3 + Q4")

ts.text <- data.frame()

for(line in table.text) {
  ts.text <- rbind(ts.text, line)
}

kbl(ts.text, col.names = NULL) %>% 
  kable_styling()
```

```{r tssummary}
#| label: tbl-ts.summary.data
#| tbl-cap: Tech savvy summary data

ts.qs <- privacy %>% 
  mutate(ts1 = as.numeric(ts1)) %>% 
  mutate(ts2 = as.numeric(ts2)) %>% 
  mutate(ts3 = as.numeric(ts3)) %>% 
  select(`Use computer skill` = ts1,
         `Fix computer skill` = ts2,
         `Program computer skill` = ts3) 

datasummary(All(ts.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=ts.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))

ts.other.q <- privacy %>% 
  select(`Facial recognition commonness` = ts4) 

datasummary_skim(ts.other.q, type="categorical")

ts.index.q <- privacy %>% 
  select(`Tech savvy index` = ts.index) 

datasummary(All(ts.index.q) ~ Mean + SD + Histogram, data=ts.index.q)
```

## Tracking

<<<<<<< HEAD
```{r trackqs}
#| label: tbl-track.q.text
#| tbl-cap: Attitudes regarding tracking questions

table.text <- list()

table.text[[1]] <- c("Q1", "How closely do you think the central government tracks your online activity?")
table.text[[2]] <- c("Q2", "How closely do you think the local government tracks your online activity?")
table.text[[3]] <- c("Q3", "How closely do you think private companies track your online activity?")
table.text[[4]] <- c("Q4", "How comfortable are you with the central government knowing personal details about your activity online?")
table.text[[5]] <- c("Q5", "How comfortable are you with the local government knowing personal details about your activity online?")
table.text[[6]] <- c("Q6", "How comfortable are you with private companies knowing personal details about your activity online?")


track.text <- data.frame()

for(line in table.text) {
  track.text <- rbind(track.text, line)
}

kbl(track.text, col.names = NULL) %>% 
  kable_styling()
```

```{r tracksummary}
#| label: tbl-track.summary.data
#| tbl-cap: Attitudes regarding tracking summary data

track.qs <- privacy %>% 
  mutate(track1 = as.numeric(track1)) %>% 
  mutate(track2 = as.numeric(track2)) %>% 
  mutate(track3 = as.numeric(track3)) %>% 
  mutate(track4 = as.numeric(track4)) %>% 
  mutate(track5 = as.numeric(track5)) %>%
  mutate(track6 = as.numeric(track6)) %>% 
  select(`Central government tracking - prevalence` = track1,
         `Local government tracking - prevalence` = track2,
         `Private company tracking - prevalence` = track3,
         `Central government tracking - comfort` = track4,
         `Local govenrment tracking - comfort` = track5,
         `Private company tracking - comfort` = track6) 

datasummary(All(track.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=track.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))
```
=======
## Miscellaneous
>>>>>>> 73c613b8a48aede63e08970ea7cd10489764b961

## Experiment results

```{r expqs}
#| label: tbl-exp.q.text
#| tbl-cap: Experiment questions

table.text <- list()

table.text[[1]] <- c("Prompt", "China's Social Credit is a new system for the Chinese government to monitor, assess and manage the behavior of all individuals, companies and non-governmental organizations in China. This large project is a response to the low levels of trust among members of society and a desire by the government to improve the behavior and law-following of all citizens. 

Right now the social credit system is being tested by many municipalities and companies -- the social credit system is slated for a nationwide roll-out in the near future. All citizens will receive a social credit identifier number and, via app technology, will be able to see their social credit score in real time as well as the reasons for having a high or low score.")

table.text[[2]] <- c("Treatment", "The social credit system will increase monitoring of people’s online behavior. The government plans to track what videos and websites a user browses and what kind of purchases a user makes, including whether they do things such as buy too many video games or other purchases the government wants to discourage. Other things tracked may include users’ search history and WeChat postings.

Right now citizens have no way of knowing which government officials or companies have access to the social credit system data. Moreover, there are no regulations on how the system can be used to limit the freedoms of individual citizens - currently low social credit scores have prevented people from buying plane and train tickets and other, more severe punishments are being considered for those with low scores.")

table.text[[3]] <- c("Q1", "I don’t believe there are any serious privacy concerns related to the social credit system.")
table.text[[4]] <- c("Q2", "I don’t think the social credit system will affect me personally.")
table.text[[5]] <- c("Q3", "I am not too worried about my private information being shared on the internet.")
table.text[[6]] <- c("Q4", "I believe companies will generally not misuse my private information.")
table.text[[7]] <- c("Q5", "I believe the government will generally not misuse my private information.")

exp.text <- data.frame()

for(line in table.text) {
  exp.text <- rbind(exp.text, line)
}

kbl(exp.text, col.names = NULL) %>% 
  kable_styling()
```

```{r expsummary}
#| label: tbl-exp.summary.data
#| tbl-cap: Experiment summary data

exp.qs <- privacy %>% 
  mutate(track1 = as.numeric(etr1)) %>% 
  mutate(track2 = as.numeric(etr2)) %>% 
  mutate(track3 = as.numeric(etr3)) %>% 
  mutate(track4 = as.numeric(etr4)) %>% 
  mutate(track5 = as.numeric(etr5)) %>%
  select(`Social credit concerns` = etr1,
         `Social credit - personally affect` = etr2,
         `General privacy concerns` = etr3,
         `Private company concerns` = etr4,
         `Government concerns` = etr5) 

datasummary(All(exp.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=exp.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))
```

## List experiment results

```{r listexpqs}
#| label: tbl-exp.q.text
#| tbl-cap: Experiment questions

table.text <- list()

table.text[[1]] <- c("Q1", "For the question below, please count how many of the entities listed below you would trust with your online personal information, such as details about your purchase history, your browsing habits, and your social media posts

•	Alibaba
•	Tencent
•	Foreign internet companies (such as Microsoft)
•	Your family
----------- LIST QUESTION BEGINS HERE ------------
•	The police")

table.text[[2]] <- c("Q2", "For the question below, please count how many of the entities listed below you would trust with your online personal information, such as details about your purchase history, your browsing habits, and your social media posts

•	Alibaba
•	Tencent
•	Foreign internet companies (such as Microsoft)
•	Your family
----------- LIST QUESTION BEGINS HERE ------------
•	The central government")

table.text[[3]] <- c("Q3", "For the question below, please count how many of the entities listed below you would trust with your online personal information, such as details about your purchase history, your browsing habits, and your social media posts

•	Alibaba
•	Tencent
•	Foreign internet companies (such as Microsoft)
•	Your family
----------- LIST QUESTION BEGINS HERE ------------
•	The local government")

listexp.text <- data.frame()

for(line in table.text) {
  listexp.text <- rbind(listexp.text, line)
}

kbl(listexp.text, col.names = NULL) %>% 
  kable_styling()
```

```{r expsummary}
#| label: tbl-exp.summary.data
#| tbl-cap: Experiment summary data

listexp.qs <- privacy %>% 
  mutate(track1 = as.numeric(etr1)) %>% 
  mutate(track2 = as.numeric(etr2)) %>% 
  mutate(track3 = as.numeric(etr3)) %>% 
  select(`Police list experiment` = etr1,
         `Central government list experiment` = etr2,
         `Local government list experiment` = ) 

datasummary(All(listexp.qs) ~ 
              Ones + Twos + Threes + Fours + Fives + Sixes + Sevens + Mean + Histogram, 
            data=listexp.qs,
            col.names = c("", "1", "2", "3", "4", "5", "6", "7", "Mean", "Histogram"))
```
